"""Delete updated_at

Revision ID: a5e5940e7395
Revises: 8e5127c3160f
Create Date: 2024-01-12 18:09:47.231907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e5940e7395'
down_revision: Union[str, None] = '8e5127c3160f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
